authors:
  klieret:
    name: Kilian Lieret
    description: ""
    avatar: https://github.com/klieret.png
    slug: https://github.com/klieret
    url: https://lieret.net
  carlosejimenez:
    name: Carlos E Jimenez
    description: ""
    avatar: https://github.com/carlosejimenez.png
    slug: https://github.com/carlosejimenez
    url: https://www.carlosejimenez.com/
  john-b-yang:
    name: John Yang
    description: ""
    avatar: https://github.com/john-b-yang.png
    slug: https://github.com/john-b-yang
    url: https://john-b-yang.github.io/
  ofirpress:
    name: Ofir Press
    description: ""
    avatar: https://github.com/ofirpress.png
    slug: https://github.com/ofirpress
    url: https://ofir.io/about/